### ISSUE TITLE
Qtcreator 4.3 error in Arch linux

### ISSUE THREAD

**Issue by alabd14313** [OneMoreGres/qtc-cppcheck#22]
When I update qtcreator in arch linux to v4.3, there is a bug:

qtcreator: relocation error: /usr/lib/qtcreator/plugins/libQtcCppcheck.so: symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5 with link time reference

I see this error in qtcGtest and qtcDbviewer too.

**Comment by OneMoreGres** [comment]
Are you running it with qtcreator.sh (which sets proper LD_LIBRARY_PATH)?

**Comment by OneMoreGres** [comment]
Checked it on arch linux.

It works if you use qt installer, downloaded from qt.io (that is my target for binaries compatibility check).

And it does not work if you install it from via pacman. Probably because it was build with different compiler version. Looks like there are some AUR packages with these plugins, so maybe you should use them.
